### ISSUE TITLE
[FEATURE] Bank ordered in tabs

### ISSUE THREAD

**Issue by m-s-will** [DanielScholte/GuildWars2Companion#45]
**Is your feature request related to a problem? Please describe.**
Users might use different bank tabs for storing different kinds of items (weapons tab, booster tab, black lion tab etc). Currently, all items are shown after another without any tab distinction. This may become cluttered with many items. 

**Describe the solution you'd like**
Show the bank as it is in game or similar to material storage and character inventories, with the acquired bank tabs and the items being ordered in them.

**Comment by DanielScholte** [comment]
The GW2 api currently does not provide the bank tabs, but only the items spread across them. See this [wiki page](https://wiki.guildwars2.com/wiki/API:2/account/bank).  
The alternative would be to show the empty item slots, as those are currently hidden. Would this be an acceptable solution?

**Comment by m-s-will** [comment]
Hm ok I didn't know if it was possible, but saw that GW2 Efficiency does something like that, but probably also through counting the empty slots. Giving an indication where a tab ends after each 30 slots would probably help with quickly finding items.

**Comment by DanielScholte** [comment]
Hmm yeah that's possible, hadn't thought of that before. I'll add it to the milestones for v1.5.
