### ISSUE TITLE
[FEATURE] Meta events upcoming overview

### ISSUE THREAD

**Issue by MikeKotte** [DanielScholte/GuildWars2Companion#64]
**Is your feature request related to a problem? Please describe.**
Currently, meta events are categorized and show per map with their timing. 

**Describe the solution you'd like**
Add a view below the categories that shows a rotation of active and upcoming meta events.

**Describe alternatives you've considered**
Creating a separate page for this or making this togglable with the current Meta Events view. I am of the opinion that there is enough space below the categories.

**Comment by DanielScholte** [comment]
Related to #13
