### ISSUE TITLE
[BUG] unreliable results for WB

### ISSUE THREAD

**Issue by bluenote73** [DanielScholte/GuildWars2Companion#70]
This happens randomly. (Sorry). Seems to have started roughly since DST came into effect again. I often check world boss schedules, and I get all manner of wrong results that refresh differently if I refresh. And even refreshing doesn't always seem to fix it. It works fine lots of the time, but it's a very clear difference. I'm sorry I can't be more specific. I hope you can fix this, love the app!

**Comment by DanielScholte** [comment]
Huh... Hadn't noticed it before, but I see it as well. Will look into it tomorrow and roll out a fix this weekend.

**Comment by DanielScholte** [comment]
Seems to affect meta events too every now and then.

**Comment by DanielScholte** [comment]
Is fixed in version 1.5.6. Both Android and iOS versions have been submitted for review.

**Comment by bluenote73** [comment]
Thank you!
